=== open-contracting-extensions/public-private-partnerships/schema/patched/release-package-schema.json
{
  "id": "https://standard.open-contracting.org/profiles/ppp/schema/1__0__0__beta5/release-package-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an Open Contracting Release Package",
  "description": "The release package contains a list of releases along with some publishing metadata.",
  "type": "object",
  "required": [
    "uri",
    "publisher",
    "publishedDate",
    "releases",
    "version"
  ],
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world. Recommended practice is to use a dereferenceable URI, where a persistent copy of this package is available.",
      "type": "string",
      "format": "uri"
    },
    "version": {
      "title": "OCDS schema version",
      "description": "The version of the OCDS schema used in this package, expressed as major.minor For example: 1.0 or 1.1",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "extensions": {
      "title": "OCDS extensions",
      "description": "An array of OCDS extensions used in this package, in which each array item is the URL of an extension.json file.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time"
    },
    "releases": {
      "title": "Releases",
      "description": "An array of one or more OCDS releases.",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "https://standard.open-contracting.org/profiles/ppp/schema/1__0__0__beta5/release-schema.json"
      },
      "uniqueItems": true
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organization or department responsible for publishing this data.",
          "type": "string"
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "required": [
        "name"
      ]
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](http://opendefinition.org/licenses/) license is recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publishers [publication policy](https://standard.open-contracting.org/{{version}}/{{lang}}/implementation/publication_policy/).",
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    }
  }
}

=== open-contracting-extensions/public-private-partnerships/docs/examples/full.json
{
  "version": "1.1",
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "extensions": [
    "https://standard.open-contracting.org/profiles/ppp/extension/1__0__0__beta5/extension.json"
  ],
  "publishedDate": "2020-01-24T00:00:00Z",
  "publisher": {
    "name": "Open Data Services Co-operative Limited",
    "scheme": "GB-COH",
    "uid": "9506232",
    "uri": "http://data.companieshouse.gov.uk/doc/company/09506232"
  },
  "uri": "https://standard.open-contracting.org/profiles/ppp/latest/en/_static/full.json",
  "releases": [
    {
      "ocid": "ocds-213czf-example-ppp",
      "id": "1.2.1",
      "language": "en",
      "date": "2015-09-30T12:09:30-06:00",
      "initiationType": "tender",
      "tag": [
        "planning"
      ],
      "parties": [
        {
          "id": "XX-GOV-12345678",
          "name": "Ministry of Communications",
          "roles": [
            "procuringEntity"
          ],
          "identifier": {
            "scheme": "XX-GOV",
            "id": "12345678",
            "legalName": "Ministry of Communications",
            "uri": "http://ministries.example.gov/012345678"
          },
          "address": {
            "streetAddress": "1 Main Street",
            "locality": "Capital City",
            "region": "Capital State",
            "postalCode": "CS 123456",
            "countryName": "Example Country"
          },
          "contactPoint": {
            "name": "Public Private Partnerships Department",
            "email": "ppps@communications.gov.example",
            "telephone": "00 00 00 00 00",
            "faxNumber": "00 00 00 00 01",
            "url": "http://ppps.communications.gov.example"
          }
        },
        {
          "id": "XX-GOV-00000000",
          "name": "Telecoms Promoter",
          "roles": [
            "buyer"
          ],
          "identifier": {
            "scheme": "XX-GOV",
            "id": "00000000",
            "legalName": "Telecoms Promoter",
            "uri": "http://ministries.gov.example/00000000"
          },
          "address": {
            "streetAddress": "1 Other Street",
            "locality": "Capital City",
            "region": "Capital State",
            "postalCode": "CS 000000",
            "countryName": "Example Country"
          },
          "contactPoint": {
            "name": "Example PPP team",
            "email": "ppps@telecompromoter.gov.example",
            "telephone": "11 11 11 11",
            "faxNumber": "11 11 11 12",
            "url": "http://telecompromoter.gov.example"
          }
        },
        {
          "id": "XX-GOV-99999999",
          "name": "National Fiber Infrastructure",
          "roles": [
            "assetProvider"
          ],
          "identifier": {
            "scheme": "XX-GOV",
            "id": "99999999",
            "legalName": "National Fiber Infrastructure",
            "uri": "http://statecompanies.gov.example/99999999"
          },
          "address": {
            "streetAddress": "99 Cable Street",
            "locality": "Capital City",
            "region": "Capital State",
            "postalCode": "CS 999999",
            "countryName": "Example Country"
          },
          "contactPoint": {
            "name": "Head Office",
            "email": "enquiries@fiber.gov.example",
            "telephone": "99 99 99 99",
            "faxNumber": "99 99 99 90",
            "url": "http://fiber.gov.example"
          }
        }
      ],
      "buyer": {
        "id": "XX-GOV-00000000",
        "name": "Telecoms Promoter"
      },
      "relatedProcesses": [
        {
          "id": "1",
          "title": "Tender for financial advisor",
          "relationship": [
            "advisor"
          ],
          "identifier": "ocds-213czf-00000-0001",
          "scheme": "ocid",
          "uri": "http://finance.example.gov/tenders/ocds-213czf-00000-0001"
        }
      ],
      "planning": {
        "budget": {
          "id": "123456789",
          "description": "Predicted public and private sector investment over the duration of the project",
          "amount": {
            "amount": 600000000,
            "currency": "USD"
          },
          "uri": "http://finance.gov.example/budget/123456789"
        },
        "rationale": "The project will increase the telecommunication services coverage, promote competitive prices and enhance the quality of services according to international standards. ",
        "project": {
          "title": "Example PPP",
          "description": "The Example PPP project will guarantee the installation of a wholesale shared network that allows the provision of telecommunications services by current and future operators.",
          "id": "example_ppp",
          "uri": "http://communications.gov.example/projects/example_ppp",
          "totalValue": {
            "amount": 600000000,
            "currency": "USD"
          },
          "sector": {
            "scheme": "COFOG",
            "description": "Communication (CS)",
            "id": "04.6.0",
            "uri": "https://unstats.un.org/unsd/cr/registry/regcs.asp?Cl=4&Lg=1&Co=04.6.0"
          },
          "locations": [
            {
              "description": "Example Country",
              "gazetteer": {
                "scheme": "GEONAMES",
                "identifiers": [
                  "0000000"
                ]
              }
            }
          ]
        },
        "forecasts": [
          {
            "id": "demand",
            "title": "Annual demand",
            "description": "Annual 4G traffic measured in gigabytes",
            "observations": [
              {
                "id": "2016",
                "measure": "815280000.0",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2016-01-01T00:00:00Z",
                  "endDate": "2016-12-31T23:59:59Z"
                }
              },
              {
                "id": "2017",
                "measure": "903365129.5706391",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2017-01-01T00:00:00Z",
                  "endDate": "2017-12-31T23:59:59Z"
                }
              },
              {
                "id": "2018",
                "measure": "1001480826.6399665",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2018-01-01T00:00:00Z",
                  "endDate": "2018-12-31T23:59:59Z"
                }
              },
              {
                "id": "2019",
                "measure": "1110825529.4633253",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2019-01-01T00:00:00Z",
                  "endDate": "2019-12-31T23:59:59Z"
                }
              },
              {
                "id": "2020",
                "measure": "1232747361.2976859",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2020-01-01T00:00:00Z",
                  "endDate": "2020-12-31T23:59:59Z"
                }
              },
              {
                "id": "2021",
                "measure": "1368763614.680674",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2021-01-01T00:00:00Z",
                  "endDate": "2021-12-31T23:59:59Z"
                }
              },
              {
                "id": "2022",
                "measure": "1520582872.0748835",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2022-01-01T00:00:00Z",
                  "endDate": "2022-12-31T23:59:59Z"
                }
              },
              {
                "id": "2023",
                "measure": "1690130132.8503568",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2023-01-01T00:00:00Z",
                  "endDate": "2023-12-31T23:59:59Z"
                }
              },
              {
                "id": "2024",
                "measure": "1879575370.3220415",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2024-01-01T00:00:00Z",
                  "endDate": "2024-12-31T23:59:59Z"
                }
              },
              {
                "id": "2025",
                "measure": "2091366004.3704107",
                "unit": {
                  "name": "gigabytes",
                  "id": "E34",
                  "scheme": "UNCEFACT"
                },
                "period": {
                  "startDate": "2025-01-01T00:00:00Z",
                  "endDate": "2025-12-31T23:59:59Z"
                }
              },
              {
                "id": "2026",
                "measure": "2328263846.301749",
                "unit": {
                  "name": "gigabytes",
